"""product model ..

Revision ID: bbd40749881f
Revises: 65e2eaff6a91
Create Date: 2024-06-11 20:09:56.839981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd40749881f'
down_revision: Union[str, None] = '65e2eaff6a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_product_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_product_id_fkey', 'product', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
