"""basket_item_amount

Revision ID: 3afe9fb6e915
Revises: 909c8ceac365
Create Date: 2024-05-17 21:13:26.569089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afe9fb6e915'
down_revision: Union[str, None] = '909c8ceac365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_items', sa.Column('amount', sa.Integer(), nullable=True))
    op.alter_column('tokens', 'access_token',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'access_token',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('basket_items', 'amount')
    # ### end Alembic commands ###
