"""Message

Revision ID: 3c0996b64479
Revises: 4645f5361a7b
Create Date: 2024-04-02 10:04:09.730592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0996b64479'
down_revision: Union[str, None] = '4645f5361a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('article', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('new_price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_hit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_hit')
    op.drop_column('products', 'new_price')
    op.drop_column('products', 'price')
    op.drop_column('product_info', 'article')
    # ### end Alembic commands ###
