"""fix product_info

Revision ID: 4645f5361a7b
Revises: 4c22d4e812ca
Create Date: 2024-03-18 16:11:17.470642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4645f5361a7b'
down_revision: Union[str, None] = '4c22d4e812ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product_property', 'products', ['prod_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_property', type_='foreignkey')
    # ### end Alembic commands ###
