"""create_date_on_product

Revision ID: 4b707982dcb0
Revises: 3cae2d6cce88
Create Date: 2024-06-04 19:07:25.426928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b707982dcb0'
down_revision: Union[str, None] = '3cae2d6cce88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('create_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'create_date')
    # ### end Alembic commands ###
