"""change name in column categories

Revision ID: 53b79f59e70c
Revises: 830b7edb4680
Create Date: 2024-03-10 21:27:54.385323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b79f59e70c'
down_revision: Union[str, None] = '830b7edb4680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sort', sa.Integer(), nullable=True))
    op.drop_column('category', 'sort_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('category', 'sort')
    # ### end Alembic commands ###
