"""add some column

Revision ID: ed3f68721cda
Revises: 3c0996b64479
Create Date: 2024-04-02 13:05:27.183310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3f68721cda'
down_revision: Union[str, None] = '3c0996b64479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('old_price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.drop_column('products', 'new_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('new_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'brand')
    op.drop_column('products', 'old_price')
    # ### end Alembic commands ###
